
export const products = [
  {
    id: "1",
    name: "T-Shirt with Tape Details",            
    price: 120,
    originalPrice: null,
    discountPercentage: null,
    type:'T-shirts',
    colour: 'red',
    sizes: ["XXS", "M", "L", "XL"],
    colors:['red', 'green'],
    image: "/images/products/shirt.png",
    images: [
      "/images/products/shirt.png",
      "/images/products/skinny-fit-jeans.png",
      "/images/products/stripped-Tshirt.png"
    ],
    categoryId: "1",
    description: "Classic checkered shirt made with breathable fabric, perfect for casual and semi-formal wear.",
    rating: 4.5,
  },
  {
    id: "2",
    name: "Skinny Fit Jeans",
    price: 240,
    originalPrice: null,
    discountPercentage: null,
    type:'Shorts',
    sizes: ["xS", "s", "L", "XL"],
    image: "/images/products/skinny-fit-jeans.png",
    categoryId: "3",
    description: "Comfortable casual sneakers",
  },
  {
    id: "3",
    name: "Checked Shirts",
    price: 180,
    originalPrice: null,
    discountPercentage: null,
    type:'Shirts',
    sizes: ["S", "XXL", "L", "XL"],
    image: "/images/products/checked-shirt.png",
    categoryId: "2",
    description: "Track your fitness and notifications",
  },
  {
    id: "4",
    name: "Sleeve Stripped T-shirt",
    price: 130,
    originalPrice: null,
    discountPercentage: null,
    type:'T-shirts',
    sizes: ["S", "M", "L", "XL"],
    image: "/images/products/stripped-Tshirt.png",
    category: "3",
    description: "Track your fitness and notifications",
  },
  {
    id: "5",
    name: "Classic Blue Denim Jeans",
    price: 260,
    originalPrice: 300,
    discountPercentage: 13,
    type: "Jeans",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/products/skinny-fit-jeans.png",
    images: [
      "/images/products/skinny-fit-jeans.png",
      "/images/products/skinny-fit-jeans.png",
    ],
    categoryId: "3",
    description: "Classic blue denim jeans with a regular fit.",
    rating: 4.4,
  },
  {
    id: "6",
    name: "Plain White T-Shirt",
    price: 90,
    originalPrice: null,
    discountPercentage: null,
    type: "Hoodies",
    sizes: ["S", "M", "L", "3XL"],
    image: "/images/products/stripped-Tshirt.png",
    images: [
      "/images/products/stripped-Tshirt.png",
      "/images/products/stripped-Tshirt.png",
    ],
    categoryId: "1",
    description: "Minimal plain white t-shirt for everyday wear.",
    rating: 4.0,
  },
  {
    id: "7",
    name: "Formal Slim Fit Shirt",
    price: 210,
    originalPrice: null,
    discountPercentage: null,
    type: "Shirts",
    sizes: ["S", "M", "L", "3XL"],
    image: "/images/products/formal-shirt.png",
    images: [
      "/images/products/formal-shirt.png",
      "/images/products/formal-shirt.png",
    ],
    categoryId: "2",
    description: "Slim fit formal shirt ideal for office and meetings.",
    rating: 4.3,
  },
  {
    id: "8",
    name: "Black Distressed Jeans",
    price: 280,
    originalPrice: 320,
    discountPercentage: 12,
    type: "Jeans",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/products/skinny-fit-jeans.png",
    images: [
      "/images/products/skinny-fit-jeans.png",
      "/images/products/skinny-fit-jeans.png",
    ],
    categoryId: "3",
    description: "Trendy black jeans with subtle distressed styling.",
    rating: 4.6,
  },
  {
    id: "9",
    name: "Printed Graphic T-Shirt",
    price: 150,
    originalPrice: null,
    discountPercentage: null,
    type: "T-shirts",
    sizes: ["S", "XS", "L", "4XL"],
    image: "/images/products/stripped-Tshirt.png",
    images: [
      "/images/products/stripped-Tshirt.png",
      "/images/products/stripped-Tshirt.png",
    ],
    categoryId: "1",
    description: "Graphic printed t-shirt with vibrant colors.",
    rating: 4.2,
  },
  {
    id: "10",
    name: "Linen Casual Shirt",
    price: 230,
    originalPrice: null,
    discountPercentage: null,
    type: "Shirts",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/products/shirt.png",
    images: [
      "/images/products/shirt.png",
      "/images/products/shirt.png",
    ],
    categoryId: "2",
    description: "Lightweight linen shirt perfect for summer wear.",
    rating: 4.5,
  },
   {
    id: "11",
    name: "Oversized Cotton T-Shirt",
    price: 160,
    originalPrice: null,
    discountPercentage: null,
    type: "T-shirts",
    sizes: ["XXS", "M", "4XL", "XL"],
    image: "/images/products/stripped-Tshirt.png",
    images: [
      "/images/products/stripped-Tshirt.png",
      "/images/products/stripped-Tshirt.png",
    ],
    categoryId: "1",
    description: "Relaxed fit oversized t-shirt made from premium cotton.",
    rating: 4.4,
  },
  {
    id: "12",
    name: "Regular Fit Blue Jeans",
    price: 250,
    originalPrice: null,
    discountPercentage: null,
    type: "Jeans",
    sizes: ["S", "M", "XL", "XL"],
    image: "/images/products/skinny-fit-jeans.png",
    images: [
      "/images/products/skinny-fit-jeans.png",
      "/images/products/skinny-fit-jeans.png",
    ],
    categoryId: "3",
    description: "Everyday regular fit jeans with durable stitching.",
    rating: 4.1,
  },
  {
    id: "13",
    name: "Half Sleeve Casual Shirt",
    price: 190,
    originalPrice: null,
    discountPercentage: null,
    type: "Shirts",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/products/shirt.png",
    images: [
      "/images/products/shirt.png",
      "/images/products/shirt.png",
    ],
    categoryId: "2",
    description: "Comfortable half sleeve shirt for daily casual wear.",
    rating: 4.0,
  },
  {
    id: "14",
    name: "Black Polo T-Shirt",
    price: 170,
    originalPrice: null,
    discountPercentage: null,
    type: "T-shirts",
    sizes: ["S", "M", "L", "3XL"],
    image: "/images/products/stripped-Tshirt.png",
    images: [
      "/images/products/stripped-Tshirt.png",
      "/images/products/stripped-Tshirt.png",
    ],
    categoryId: "1",
    description: "Classic polo t-shirt with a modern slim fit.",
    rating: 4.3,
  },
  {
    id: "15",
    name: "Light Wash Denim Jeans",
    price: 270,
    originalPrice: 310,
    discountPercentage: 13,
    type: "Jeans",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/products/skinny-fit-jeans.png",
    images: [
      "/images/products/skinny-fit-jeans.png",
      "/images/products/skinny-fit-jeans.png",
    ],
    categoryId: "3",
    description: "Light wash jeans with a fresh casual look.",
    rating: 4.5,
  },
  {
    id: "16",
    name: "Printed Casual Shirt",
    price: 200,
    originalPrice: null,
    discountPercentage: null,
    type: "Shirts",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/products/shirt.png",
    images: [
      "/images/products/shirt.png",
      "/images/products/shirt.png",
    ],
    categoryId: "2",
    description: "Printed shirt with soft fabric and vibrant patterns.",
    rating: 4.2,
  },
  {
    id: "17",
    name: "Round Neck Solid T-Shirt",
    price: 110,
    originalPrice: null,
    discountPercentage: null,
    type: "T-shirts",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/products/stripped-Tshirt.png",
    images: [
      "/images/products/stripped-Tshirt.png",
      "/images/products/stripped-Tshirt.png",
    ],
    categoryId: "4",
    description: "Solid color round neck t-shirt for everyday comfort.",
    rating: 4.0,
  },
  {
    id: "18",
    name: "Stretch Fit Grey Jeans",
    price: 260,
    originalPrice: null,
    discountPercentage: null,
    type: "Jeans",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/products/skinny-fit-jeans.png",
    images: [
      "/images/products/skinny-fit-jeans.png",
      "/images/products/skinny-fit-jeans.png",
    ],
    categoryId: "4",
    description: "Stretchable grey jeans offering flexibility and style.",
    rating: 4.4,
  },
  {
    id: "19",
    name: "Slim Fit Oxford Shirt",
    price: 220,
    originalPrice: null,
    discountPercentage: null,
    type: "Shirts",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/products/shirt.png",
    images: [
      "/images/products/shirt.png",
      "/images/products/shirt.png",
    ],
    categoryId: "2",
    description: "Oxford fabric slim fit shirt for smart casual outfits.",
    rating: 4.6,
  },
  {
    id: "20",
    name: "Color Block T-Shirt",
    price: 140,
    originalPrice: null,
    discountPercentage: null,
    type: "T-shirts",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/products/stripped-Tshirt.png",
    images: [
      "/images/products/stripped-Tshirt.png",
      "/images/products/stripped-Tshirt.png",
    ],
    categoryId: "4",
    description: "Trendy color block t-shirt with a modern design.",
    rating: 4.1,
  },
  // {
  //   "id": "7b2a6c4e-3e5a-4c91-b8a7-2f9c6d1a0011",
  //   "name": "Oversized Black T-Shirt",
  //   "price": 799,
  //   "rating": 4.5,
  //   "categoryId": "c2a6b7e1-8d74-4e9c-91a5-3a7d9e9cee55",
  //   "image": "/images/products/black-tshirt.jpg",
  //   "images": [
  //     "/images/products/black-tshirt-1.jpg",
  //     "/images/products/black-tshirt-2.jpg",
  //     "/images/products/black-tshirt-3.jpg"
  //   ],
  //   "brand": "Veetee",
  //   "sizes": ["S", "M", "L", "XL"],
  //   "colors": ["Black"],
  //   "stock": 25
  // },
  // {
  //   "id": "9a1c7d2e-4f8a-4c9a-8d1e-7c2b9e0a0022",
  //   "name": "White Printed T-Shirt",
  //   "price": 699,
  //   "rating": 0,
  //   "categoryId": "c2a6b7e1-8d74-4e9c-91a5-3a7d9e9cee55",
  //   "image": "/images/products/white-tshirt.jpg",
  //   "images": [],
  //   "brand": "Veetee",
  //   "sizes": ["M", "L", "XL"],
  //   "colors": ["White"],
  //   "stock": 40
  // },
  // {
  //   "id": "4e9a6c1b-8d7a-4f2a-9c11-2b6e7d9a0033",
  //   "name": "Men Slim Fit Shirt",
  //   "price": 1299,
  //   "rating": 4,
  //   "categoryId": "e91b6c3a-9d6f-4a42-bf71-6c2d7c1eea66",
  //   "image": "/images/products/shirt.jpg",
  //   "brand": "Veetee",
  //   "sizes": ["M", "L", "XL"],
  //   "colors": ["Blue", "White"],
  //   "stock": 15
  // }
];

export const getProductById = (id) => {
  return new Promise((resolve,reject) => {
    setTimeout(() => {
      const product = products.find(p => p.id === id);

      if(!product) {
      reject(new Error("Product not found"));
     } else {
      resolve(product);
     }
    }, 1000)
  });
};
